"""add snomed concept terms

Revision ID: 43b1e3b20443
Revises: 596749e14960
Create Date: 2026-08-23 17:25:20.982525
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '43b1e3b20443'
down_revision: Union[str, None] = '596749e14960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snomed_concept_term',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('release_version', sa.String(length=64), nullable=False),
    sa.Column('concept_id', sa.String(length=24), nullable=False),
    sa.Column('fsn', sa.Text(), nullable=True),
    sa.Column('preferred_term', sa.Text(), nullable=True),
    sa.Column('language_refset_id', sa.String(length=24), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['terminology_release.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concept_id', 'release_version', name='uq_snomed_term_concept_release')
    )
    with op.batch_alter_table('snomed_concept_term', schema=None) as batch_op:
        batch_op.create_index('ix_snomed_term_release_concept', ['release_version', 'concept_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snomed_concept_term', schema=None) as batch_op:
        batch_op.drop_index('ix_snomed_term_release_concept')

    op.drop_table('snomed_concept_term')
    # ### end Alembic commands ###
