"""initial terminology schema

Revision ID: 596749e14960
Revises: 
Create Date: 2026-08-23 15:07:40.959238
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '596749e14960'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('loinc_version', sa.String(length=64), nullable=True),
    sa.Column('snomed_version', sa.String(length=64), nullable=True),
    sa.Column('mapping_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('scope_json', sa.JSON(), nullable=True),
    sa.Column('report_path', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('local_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_dataset', sa.String(length=64), nullable=False),
    sa.Column('source_system', sa.String(length=128), nullable=True),
    sa.Column('local_code', sa.String(length=128), nullable=False),
    sa.Column('local_text', sa.Text(), nullable=False),
    sa.Column('local_context_json', sa.JSON(), nullable=True),
    sa.Column('target_system', sa.String(length=32), nullable=False),
    sa.Column('target_code', sa.String(length=32), nullable=False),
    sa.Column('target_display', sa.Text(), nullable=True),
    sa.Column('mapped_against_version', sa.String(length=64), nullable=True),
    sa.Column('map_correlation', sa.String(length=32), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_dataset', 'local_code', 'target_system', name='uq_local_mapping_dataset_code_system')
    )
    with op.batch_alter_table('local_mapping', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_local_mapping_source_dataset'), ['source_dataset'], unique=False)
        batch_op.create_index('ix_local_mapping_target', ['target_system', 'target_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_local_mapping_target_system'), ['target_system'], unique=False)

    op.create_table('terminology_release',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('source_filename', sa.String(length=512), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('import_status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('system', 'sha256', name='uq_release_system_sha256'),
    sa.UniqueConstraint('system', 'version', name='uq_release_system_version')
    )
    with op.batch_alter_table('terminology_release', schema=None) as batch_op:
        batch_op.create_index('ix_release_system_current', ['system', 'is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_terminology_release_system'), ['system'], unique=False)

    op.create_table('audit_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_run_id', sa.Integer(), nullable=False),
    sa.Column('mapping_id', sa.Integer(), nullable=True),
    sa.Column('target_system', sa.String(length=32), nullable=False),
    sa.Column('old_code', sa.String(length=32), nullable=False),
    sa.Column('current_version', sa.String(length=64), nullable=True),
    sa.Column('terminology_status', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('suggested_targets_json', sa.JSON(), nullable=True),
    sa.Column('reason', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_run_id'], ['audit_run.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mapping_id'], ['local_mapping.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_result_audit_run_id'), ['audit_run_id'], unique=False)
        batch_op.create_index('ix_audit_result_code', ['target_system', 'old_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_result_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_result_mapping_id'), ['mapping_id'], unique=False)
        batch_op.create_index('ix_audit_result_run_decision', ['audit_run_id', 'decision'], unique=False)

    op.create_table('loinc_change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('release_version', sa.String(length=64), nullable=False),
    sa.Column('loinc_num', sa.String(length=32), nullable=False),
    sa.Column('property', sa.String(length=128), nullable=False),
    sa.Column('value_prior', sa.Text(), nullable=True),
    sa.Column('value_current', sa.Text(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['terminology_release.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loinc_change', schema=None) as batch_op:
        batch_op.create_index('ix_loinc_change_release_code', ['release_version', 'loinc_num'], unique=False)
        batch_op.create_index('ix_loinc_change_release_prop', ['release_version', 'property'], unique=False)

    op.create_table('loinc_concept_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('release_version', sa.String(length=64), nullable=False),
    sa.Column('loinc_num', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('long_common_name', sa.Text(), nullable=True),
    sa.Column('short_name', sa.Text(), nullable=True),
    sa.Column('component', sa.Text(), nullable=True),
    sa.Column('property', sa.String(length=128), nullable=True),
    sa.Column('time_aspect', sa.String(length=128), nullable=True),
    sa.Column('system', sa.String(length=256), nullable=True),
    sa.Column('scale_type', sa.String(length=128), nullable=True),
    sa.Column('method_type', sa.String(length=256), nullable=True),
    sa.Column('class_name', sa.String(length=128), nullable=True),
    sa.Column('change_type', sa.String(length=32), nullable=True),
    sa.Column('version_first_released', sa.String(length=32), nullable=True),
    sa.Column('version_last_changed', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['terminology_release.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loinc_num', 'release_version', name='uq_loinc_concept_code_release')
    )
    with op.batch_alter_table('loinc_concept_version', schema=None) as batch_op:
        batch_op.create_index('ix_loinc_concept_code', ['loinc_num'], unique=False)
        batch_op.create_index('ix_loinc_concept_release_code', ['release_version', 'loinc_num'], unique=False)
        batch_op.create_index('ix_loinc_concept_release_status', ['release_version', 'status'], unique=False)

    op.create_table('loinc_map_to',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('release_version', sa.String(length=64), nullable=False),
    sa.Column('source_loinc', sa.String(length=32), nullable=False),
    sa.Column('target_loinc', sa.String(length=32), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['terminology_release.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_loinc', 'target_loinc', 'release_version', name='uq_loinc_mapto_pair_release')
    )
    with op.batch_alter_table('loinc_map_to', schema=None) as batch_op:
        batch_op.create_index('ix_loinc_mapto_source', ['release_version', 'source_loinc'], unique=False)

    op.create_table('snomed_concept_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('release_version', sa.String(length=64), nullable=False),
    sa.Column('concept_id', sa.String(length=24), nullable=False),
    sa.Column('effective_time', sa.String(length=8), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('module_id', sa.String(length=24), nullable=True),
    sa.Column('definition_status_id', sa.String(length=24), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['terminology_release.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concept_id', 'release_version', name='uq_snomed_concept_release')
    )
    with op.batch_alter_table('snomed_concept_version', schema=None) as batch_op:
        batch_op.create_index('ix_snomed_concept_id', ['concept_id'], unique=False)
        batch_op.create_index('ix_snomed_concept_release_active', ['release_version', 'active'], unique=False)

    op.create_table('snomed_historical_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('release_version', sa.String(length=64), nullable=False),
    sa.Column('member_id', sa.String(length=64), nullable=True),
    sa.Column('refset_id', sa.String(length=24), nullable=False),
    sa.Column('referenced_component_id', sa.String(length=24), nullable=False),
    sa.Column('target_component_id', sa.String(length=24), nullable=False),
    sa.Column('effective_time', sa.String(length=8), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['terminology_release.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'release_version', name='uq_snomed_assoc_member_release')
    )
    with op.batch_alter_table('snomed_historical_association', schema=None) as batch_op:
        batch_op.create_index('ix_snomed_assoc_refset', ['release_version', 'refset_id'], unique=False)
        batch_op.create_index('ix_snomed_assoc_source', ['release_version', 'referenced_component_id', 'active'], unique=False)

    op.create_table('snomed_inactivation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('release_version', sa.String(length=64), nullable=False),
    sa.Column('member_id', sa.String(length=64), nullable=True),
    sa.Column('concept_id', sa.String(length=24), nullable=False),
    sa.Column('value_id', sa.String(length=24), nullable=False),
    sa.Column('effective_time', sa.String(length=8), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['terminology_release.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'release_version', name='uq_snomed_inactivation_member_release')
    )
    with op.batch_alter_table('snomed_inactivation', schema=None) as batch_op:
        batch_op.create_index('ix_snomed_inactivation_concept', ['release_version', 'concept_id', 'active'], unique=False)

    op.create_table('mapping_revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mapping_id', sa.Integer(), nullable=False),
    sa.Column('old_target_code', sa.String(length=32), nullable=True),
    sa.Column('old_target_version', sa.String(length=64), nullable=True),
    sa.Column('new_target_code', sa.String(length=32), nullable=True),
    sa.Column('new_target_version', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('audit_result_id', sa.Integer(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(length=128), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_result_id'], ['audit_result.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mapping_id'], ['local_mapping.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mapping_revision', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mapping_revision_mapping_id'), ['mapping_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mapping_revision', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mapping_revision_mapping_id'))

    op.drop_table('mapping_revision')
    with op.batch_alter_table('snomed_inactivation', schema=None) as batch_op:
        batch_op.drop_index('ix_snomed_inactivation_concept')

    op.drop_table('snomed_inactivation')
    with op.batch_alter_table('snomed_historical_association', schema=None) as batch_op:
        batch_op.drop_index('ix_snomed_assoc_source')
        batch_op.drop_index('ix_snomed_assoc_refset')

    op.drop_table('snomed_historical_association')
    with op.batch_alter_table('snomed_concept_version', schema=None) as batch_op:
        batch_op.drop_index('ix_snomed_concept_release_active')
        batch_op.drop_index('ix_snomed_concept_id')

    op.drop_table('snomed_concept_version')
    with op.batch_alter_table('loinc_map_to', schema=None) as batch_op:
        batch_op.drop_index('ix_loinc_mapto_source')

    op.drop_table('loinc_map_to')
    with op.batch_alter_table('loinc_concept_version', schema=None) as batch_op:
        batch_op.drop_index('ix_loinc_concept_release_status')
        batch_op.drop_index('ix_loinc_concept_release_code')
        batch_op.drop_index('ix_loinc_concept_code')

    op.drop_table('loinc_concept_version')
    with op.batch_alter_table('loinc_change', schema=None) as batch_op:
        batch_op.drop_index('ix_loinc_change_release_prop')
        batch_op.drop_index('ix_loinc_change_release_code')

    op.drop_table('loinc_change')
    with op.batch_alter_table('audit_result', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_result_run_decision')
        batch_op.drop_index(batch_op.f('ix_audit_result_mapping_id'))
        batch_op.drop_index(batch_op.f('ix_audit_result_decision'))
        batch_op.drop_index('ix_audit_result_code')
        batch_op.drop_index(batch_op.f('ix_audit_result_audit_run_id'))

    op.drop_table('audit_result')
    with op.batch_alter_table('terminology_release', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_terminology_release_system'))
        batch_op.drop_index('ix_release_system_current')

    op.drop_table('terminology_release')
    with op.batch_alter_table('local_mapping', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_local_mapping_target_system'))
        batch_op.drop_index('ix_local_mapping_target')
        batch_op.drop_index(batch_op.f('ix_local_mapping_source_dataset'))

    op.drop_table('local_mapping')
    op.drop_table('audit_run')
    # ### end Alembic commands ###
